# Generated by Django 2.2.4 on 2019-08-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_uwi', models.CharField(max_length=19)),
                ('w_name', models.CharField(blank=True, max_length=100, null=True)),
                ('w_drillers_total_depth', models.FloatField(blank=True, null=True)),
                ('w_operator', models.CharField(blank=True, max_length=100, null=True)),
                ('w_current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('w_province', models.CharField(blank=True, max_length=20, null=True)),
                ('w_class', models.CharField(blank=True, max_length=100, null=True)),
                ('w_bottom_lng', models.FloatField(blank=True, null=True)),
                ('w_bottom_lat', models.FloatField(blank=True, null=True)),
                ('w_top_lng', models.FloatField(blank=True, null=True)),
                ('w_top_lat', models.FloatField(blank=True, null=True)),
                ('w_pad', models.CharField(blank=True, max_length=5, null=True)),
                ('w_number_in_pad', models.CharField(blank=True, max_length=3, null=True)),
                ('w_type', models.CharField(blank=True, max_length=10, null=True)),
                ('w_injection_months', models.IntegerField(blank=True, null=True)),
                ('w_producion_months', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wells',
                'managed': False,
            },
        ),
    ]
